language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t rakshak1344/docker-react -f Dockerfile.dev . 

scripts:
  - docker run -e CI=true rakshak1344/docker-react npm run test